/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author abate, Gomez Heber , Galan Federico, Carreño Lucas
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal () {
        initComponents();
        setLocationRelativeTo(null);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemFormulariosMaterias = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemFormulariosAlumno = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemFormulariodeInscripcion = new javax.swing.JMenuItem();
        JMenuNotas = new javax.swing.JMenu();
        jMenuNotas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Materias");

        jMenuItemFormulariosMaterias.setText("Formularios de Materias");
        jMenuItemFormulariosMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormulariosMateriasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemFormulariosMaterias);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Alumnos");

        jMenuItemFormulariosAlumno.setText("Formularios de Alumno");
        jMenuItemFormulariosAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormulariosAlumnoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemFormulariosAlumno);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Inscripciones");

        jMenuItemFormulariodeInscripcion.setText("Formulario de Inscripciones");
        jMenuItemFormulariodeInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormulariodeInscripcionActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemFormulariodeInscripcion);

        jMenuBar1.add(jMenu5);

        JMenuNotas.setText("Carga de Notas");
        JMenuNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuNotasMouseClicked(evt);
            }
        });
        JMenuNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuNotasActionPerformed(evt);
            }
        });

        jMenuNotas.setText("Cargar y Edicion");
        jMenuNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNotasActionPerformed(evt);
            }
        });
        JMenuNotas.add(jMenuNotas);

        jMenuBar1.add(JMenuNotas);

        jMenu7.setText("Consultas");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemFormulariodeInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormulariodeInscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFormulariodeInscripcionActionPerformed

    private void jMenuItemFormulariosMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormulariosMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFormulariosMateriasActionPerformed

    private void jMenuItemFormulariosAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormulariosAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFormulariosAlumnoActionPerformed

    private void JMenuNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuNotasActionPerformed

    }//GEN-LAST:event_JMenuNotasActionPerformed

    private void JMenuNotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuNotasMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_JMenuNotasMouseClicked

    private void jMenuNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNotasActionPerformed
        // TODO add your handling code here:
        Escritorio.removeAll();
        Escritorio.repaint(); 
        VistaCargaNotas vi = new VistaCargaNotas();
        vi.setVisible(true);
        Escritorio.add(vi);
        Escritorio.moveToFront(vi);
    }//GEN-LAST:event_jMenuNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).
                log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).
                log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).
                log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).
                log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run () {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu JMenuNotas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemFormulariodeInscripcion;
    private javax.swing.JMenuItem jMenuItemFormulariosAlumno;
    private javax.swing.JMenuItem jMenuItemFormulariosMaterias;
    private javax.swing.JMenuItem jMenuNotas;
    // End of variables declaration//GEN-END:variables
}
